"""add quantity to order_products

Revision ID: fd46b0781461
Revises: 81ba850b3f42
Create Date: 2026-08-25 22:36:58.110662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd46b0781461'
down_revision = '81ba850b3f42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.Integer(), nullable=False, server_default='1'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_products', schema=None) as batch_op:
        batch_op.drop_column('quantity')

    # ### end Alembic commands ###
